services:
  app:
    container_name: app_effmob
    build: ./
    ports:
     - "8081:8080"
    env_file:
      - .env
    restart: always
    links:
     - postgres

  postgres:
    container_name: ml_db
    image: postgres:15.6-bookworm
    restart: always
    ports:
     - "15432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env