services:
  app:
    container_name: app_effmob
    build: ../..
    environment:
      RUN_ADDR: 0.0.0.0:8080
      LOG_LEVEL: DEBUG
      DATABASE_DSN: postgres://effmob:effmob@localhost:5432/music_lib_db
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    links:
     - postgres

  postgres:
    container_name: music_lib_db
    image: postgres:15.6-bookworm
    restart: always
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=effmob
     - POSTGRES_USER=effmob
     - POSTGRES_DB=music_lib_db