# Add song
POST http://localhost:8080/add
Content-Type: application/json

{
 "group": "Muse",
 "song": "Supermassive Black Hole"
}


### Delete Song
DELETE http://localhost:8080/delete/bfaa3ad1-2a8c-4c58-a7d6-4f3f913c37e6

### Update song
PATCH http://localhost:8080/update/bfaa3ad1-2a8c-4c58-a7d6-4f3f913c37e6
Content-Type: application/json

{
 "group": "Muse",
 "song": "Supermassive Black Hole"
}

### Get songs by filter
POST http://localhost:8080/songs
Content-Type: application/json

{
    "page": 1,
    "per_page": 8,
    "group": "Muse"
}