### Add song
POST http://localhost:8000/add
Content-Type: application/json

{
 "group": "Muse",
 "song": "Supermassive Black Hole"
}

### Delete Song
DELETE http://localhost:8000/delete/4

### Update song
PATCH http://localhost:8000/update/3
Content-Type: application/json

{
 "group": "SOAD",
 "song": "Toxicity"
}

### Get songs by filter song_name
POST http://localhost:8000/songs
Content-Type: application/json

{
    "page": 1,
    "per_page": 8,
    "song_name": "Supermassive Black Hole"
}

### Get songs by filter group_name
POST http://localhost:8000/songs
Content-Type: application/json

{
    "page": 1,
    "per_page": 8,
    "group_name": "SOAD"
}

### Get paginated song text by id
POST http://localhost:8000/songtext/1
Content-Type: application/json

{
    "page": 1,
    "per_page": 8,
    "id": 1
}