### Add song
POST http://localhost:8000/add
Content-Type: application/json

{
 "group": "Muse",
 "song": "Supermassive Black Hole"
}

### Delete Song
DELETE http://localhost:8000/delete/4

### Update song
PATCH http://localhost:8000/update/5
Content-Type: application/json

{
 "group": "SOAD",
 "song": "Toxicity"
}

### Get songs by filter
POST http://localhost:8000/songs
Content-Type: application/json

{
    "page": 1,
    "per_page": 8,
    "group": "Muse"
}

###