# Add song
POST http://localhost:8080/add
Content-Type: application/json

{
 "group": "Muse",
 "song": "Supermassive Black Hole"
}


### Delete Song
DELETE http://localhost:8080/delete/595720e3-7dc3-46c4-a262-a2845781d042

### Update song
PATCH http://localhost:8080/update/595720e3-7dc3-46c4-a262-a2845781d042
Content-Type: application/json

{
 "group": "Muse",
 "song": "Supermassive Black Hole"
}

### Get songs by filter
GET http://localhost:8080/songs
Content-Type: application/json

{
    "group": "Muse"
}